### ISSUE TITLE
CPU temperature not updated when running on batteries

### ISSUE THREAD

**Issue by mpersano** [groeck/i8k#4]
On my Inspiron 15 5000 (DMI: Dell Inc. Inspiron 5548/0YDTG3, BIOS A05 07/27/2015), the CPU temperature reported by /proc/i8k is only updated while AC power is connected. When running on batteries, the temperature reading is not updated. For instance, when performing a CPU-intensive task with the laptop running on batteries:

<pre><code>$ cat /sys/class/thermal/thermal_zone0/temp
72000

$ cat /proc/i8k
1.0 A05 406RB92 62 -22 1 -22 2900 -1 -22
</code></pre>

62 was the temperature when AC power was disconnected, after which it didn't get updated again. While the laptop is running on AC power the temperatures reported by /proc/i8k and /sys match, as expected.

Unfortunately this breaks i8kmon while the laptop is running on batteries, which relies on the CPU temperatures reported by this driver to adjust fan speed.

**Comment by groeck** [comment]
On Fri, Nov 17, 2017 at 06:26:37PM +0000, Mauro Persano wrote:
> On my Inspiron 15 5000 (DMI: Dell Inc. Inspiron 5548/0YDTG3, BIOS A05 07/27/2015), the CPU temperature reported by /proc/i8k is only updated while AC power is connected. When running on batteries, the temperature reading is not updated. For instance, when performing a CPU-intensive task with my laptop running on batteries:
> 
> <pre><code>
> $ cat /sys/class/thermal/thermal_zone0/temp
> 72000
> 
> $ cat /proc/i8k
> 1.0 A05 406RB92 62 -22 1 -22 2900 -1 -22
> </code></pre>
> 
> 62 was the temperature when AC power was disconnected, after which it didn't get updated again. While the laptop is running on AC power the temperatures reported by /proc/i8k and /sys match as expected.
> 
> Unfortunately this breaks i8kmon, which relies on the CPU temperatures reported by this driver to adjust fan speed...

Pali, is there anything we can do about that ? I don't think so, but maybe
I am wrong.

Guenter

**Comment by groeck** [comment]
On Friday 17 November 2017 15:47:39 Guenter Roeck wrote:
> On Fri, Nov 17, 2017 at 06:26:37PM +0000, Mauro Persano wrote:
> > On my Inspiron 15 5000 (DMI: Dell Inc. Inspiron 5548/0YDTG3, BIOS A05 07/27/2015), the CPU temperature reported by /proc/i8k is only updated while AC power is connected. When running on batteries, the temperature reading is not updated. For instance, when performing a CPU-intensive task with my laptop running on batteries:
> > 
> > <pre><code>
> > $ cat /sys/class/thermal/thermal_zone0/temp
> > 72000
> > 
> > $ cat /proc/i8k
> > 1.0 A05 406RB92 62 -22 1 -22 2900 -1 -22
> > </code></pre>
> > 
> > 62 was the temperature when AC power was disconnected, after which it didn't get updated again. While the laptop is running on AC power the temperatures reported by /proc/i8k and /sys match as expected.
> > 
> > Unfortunately this breaks i8kmon, which relies on the CPU temperatures reported by this driver to adjust fan speed...
> 
> Pali, is there anything we can do about that ? I don't think so, but maybe
> I am wrong.
> 
> Guenter

Temperature is reported by Dell BIOS/firmware. If it tells that
temperature is 62° and it is not truth then problem is in Dell
BIOS/firmware.

This looks like a BIOS/firmware bug, so the only thing you can
do is to report bug to Dell.

**Comment by groeck** [comment]
Nothing we can do about this problem. Note that the Dell SMM API is old and may not be well maintained by Dell; it might make sense to find another means for fan control (FWIW, automatic fan control works quite well on my Dell laptops).

**Comment by mpersano** [comment]
Thank you. I was having trouble with the fan never turning off on automatic control when AC is unplugged, so I decided to give i8kmon a try. I'll try to update the BIOS to see if it changes anything.

Thanks again!
